### ISSUE TITLE
Auto-complete company information during new job creation

### ISSUE THREAD

**Issue by ksaitor** [cryptojobslist/frontend#15]
Customer:
> Also, have you ever considered making the name of the company, the company description and the name of the poster auto-populate? If I am posting 10+ jobs, it gets tedious having to fill that in every time. LinkedIn and Glassdoor automate all of that for me. 

API endpoint `https://cryptojobslist.com/company/find?q=coinbase`

**Comment by Kr1an** [comment]
https://github.com/cryptojobslist/frontend/tree/feature/create-job-autocomplete

**Comment by ksaitor** [comment]
![screen shot 2018-06-27 at 11 12 23 am](https://user-images.githubusercontent.com/936436/41958470-2f8f6658-79fb-11e8-95c6-9edb310ecbbe.jpg)

**Comment by Kr1an** [comment]
### Technical
- Search for each character could be helpfull: google search is the example of such practice.
- Agree with request cancelling. Not logic just ignores old request that was overriden, but for efficiency its better to cancel Request, not just ignore.
### UX
- Placeholder: yes, i did not pay enough attention to it because i did not change anything, but it seems, old placeholder url is not working https://react.semantic-ui.com/assets/images/wireframe/white-image.png
- Image url input is one thing that i missed from inputs . Will be fixed soon
- Did not get the meaning of the last one: which "minor but not acceptable" bug you are talking about?

**Comment by Kr1an** [comment]
### UX
- "minor, but not acceptable": looks like its your browser specific thing. Anyway, i remove left action button and now this input's not different from others. So it should not have this issue anymore.
- I fix placeholder image. Replaced it for official semantic-ui placeholder https://cdn.jsdelivr.net/npm/semantic-ui@2.3.0/examples/assets/images/wireframe/white-image.png

**Comment by Kr1an** [comment]
https://github.com/cryptojobslist/frontend/commit/cc90c04d42fc2b326b2c0f4399ec7b39fb3b2346

**Comment by ksaitor** [comment]
👍 
Thanks for the progress. Getting closer to have a great UX with minimal clicks.
- ok. understood all your points. fair.
- re: search conditions: i'm implemented minimal query length check on the backend. That should do.
- [ ]  tested in Safari — not working there… 🤔  might be a problem. Our browser breakdown:
![screen shot 2018-06-28 at 12 08 26 pm](https://user-images.githubusercontent.com/936436/42021616-2b81c48a-7acc-11e8-9c32-dd726906de26.jpg)

- re: "In case of very poor internet connection, react app wont load itself." — we'll have to work on that soon too :)  The app is 474kb now, when built and compressed. Perhaps we should look into improving dependency sizes and optimise soon. 

- [ ] Code quality. I'll do more review, but so far:
   - `autoComplete.data.filter(x ...` line looks pretty scary. Better be refactored. 
   - whole `onChange={(e) => {…` block. Should we decouple it somewhere?

**Comment by ksaitor** [comment]
- [ ] Please, include company id in new job model. E.g. `company: "5b27f567eea16f01556e3479"`

**Comment by ksaitor** [comment]
@Kr1an  thanks for the updates.
I did some more refactoring and pushed. Feel free to check them out.
I'll be merging these soon
